### ISSUE TITLE
Build Pipelines

### ISSUE THREAD

**Issue by ashermancinelli** [IntelliTect-Samples/EWU-CSCD371-2019-Fall#158]
Could we get the azure pipeline as a travis/circle build so we can see linting/building/testing checks in the pr? Would be more helpful than having to go into the azure build to see the checks as opposed to seeing the results integrated into the pr itself.

**Comment by COsborn2** [comment]
To clarify, you're saying you want the build pipeline output as something like a comment inside of the PR? The pipeline will run "linting" as part of the build if an analyzer package is brought in. Looking at your PR, it looks like you successfully brought in the FxCopAnalyzer package.

I wouldn't recommend downgrading to something like Travis/Circle. CSharp support is community supported on Travis, and thus it has to build the NET Core 3 environment everytime. Builds can easily take more than 10 minutes. I do like Travis and use it on personal projects, but DevOps is a much better solution in this case IMO. Maybe a GitHub action to grab the build log and post as a comment? @Keboo

**Comment by ashermancinelli** [comment]
> Maybe a GitHub action to grab the build log and post as a comment?
Sounds like a great idea to me!

**Comment by Keboo** [comment]
So in regards to the quicker feedback from the pipeline. Part of the issue is the number of changes being pushed to PRs. Each time a new PR change is pushed it is queueing up a pipeline build request. Because we are running on the free tier of Azure Dev Ops, this means that we only have a single build agent (ie. only one computer), to do these builds. So when you do a push, the time needed for the build to run and complete will vary wildly based on the number of other changes in the queue in front of you. The only difference I see with Travis is the OSS offering gives three concurrent build jobs.

**Comment by ashermancinelli** [comment]
> Because we are running on the free tier of Azure...

Gotcha. Don't see better way to do this on the free tier.
